name: fkill
version: '3.7.0'
summary: Fabulously kill processes. Cross-platform.
description: |
  A command-line tool for easily and quickly killing processes.

grade: devel
confinement: strict

apps:
  fkill:
    command: fkill

parts:
  fkill:
    plugin: nodejs
    source: https://github.com/sindresorhus/fkill-cli.git
    source-tag: 'v3.7.0'
